spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mp&useSSl=false
    password: "123456"
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      aop-patterns: com.lyy.admin.*
      filters: stat,wall,slf4j
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  jdbc:
    template:
      query-timeout: 3
#    type: com.zaxxer.hikari.HikariDataSource